### PR TITLE
VS_ConstPower = 1

### PR DESCRIPTION
**Pull request by ptrbortolotti**
Switch ROSCO logic from constant torque to constant power

comparison

### CODE REVIEW

**Comment by ptrbortolotti** [comment]
@fzahle is this what the DTU controller does? @dzalkind what's more realistic?

**Comment by fzahle** [comment]
@tkbadtu you are better suited for answering the above question, thanks!

**Comment by tkbadtu** [comment]
DTU-WEC uses a blend of constant torque and constant power, in this model it's 0.9 (mostly constant power).

**Review by dzalkind — APPROVED** [review]
These results look as expected.  ROSCO doesn't (yet) blend constant torque/power, but that's good to know!

**Pull request merged**
